name: bstock
description: A stock trading app called b-stock
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # di
  injectable: ^2.1.0
  get_it: ^7.2.0

  # state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0

  # databases
  floor: ^1.4.1
  sqflite: ^2.2.4+1
  flutter_secure_storage: ^8.0.0

  # ui
  flutter_svg: ^2.0.7

  # other
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator:
  floor_generator:
  build_runner:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/font/
    - assets/icon/

  fonts:
    - family: nunito
      fonts:
        - asset: assets/font/nunito-bold.ttf
          weight: 700
        - asset: assets/font/nunito-light.ttf
          weight: 300
        - asset: assets/font/nunito-medium.ttf
          weight: 500
        - asset: assets/font/nunito-regular.ttf
          weight: 400

